name: "nextjs-starter"

services:
  app:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    container_name: app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - path: ../../.env
        required: true
    networks:
      - app-network
    ports:
      - "3000:3000"

  # Only for local development
  # Ideally, you should use a managed database service
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../src/infrastructure/persistence/migrations:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    name: nextjs-starter_postgres_data
