import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { PropsWithChildren } from "react";

import { ReactQueryProvider } from "~/app/components/providers/react-query";
import { Toaster } from "~/app/components/ui/sonner";
import { cn } from "~/app/libs/utils";
import "~/app/styles/globals.css";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create Next App",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={cn("font-sans", fontSans.variable)}>
        <ReactQueryProvider>
          {children}
          <Toaster richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
