import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "NextJS starter",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  );
}
