import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { unstable_setRequestLocale } from "next-intl/server";
import type { PropsWithChildren } from "react";

import "~/assets/css/globals.css";
import { ThemeProvider } from "~/components/theme-provider";
import { Toaster } from "~/components/ui/sonner";
import { appConfig } from "~/libs/i18n/app-config";
import { ReactQueryProvider } from "~/libs/react-query/provider";
import { cn } from "~/libs/utils";

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "NextJS starter",
};

export function generateStaticParams() {
  return appConfig.locales.map((locale) => ({ locale }));
}

export default function MainLayout({
  children,
  params: { locale },
}: PropsWithChildren<{ params: { locale: string } }>) {
  unstable_setRequestLocale(locale);

  const messages = useMessages();

  return (
    <html lang={locale} className={cn("font-sans", GeistSans.variable)}>
      <body>
        <ReactQueryProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster richColors />
            </ThemeProvider>
          </NextIntlClientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
